# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='acmContestsTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='acmContestsTeamsImages')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='acmContestsTeamsImagesThumbnail')),
                ('teamMembers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('problems', models.FileField(upload_to='')),
                ('judgesData', models.FileField(upload_to='')),
                ('rankingPhoto', models.ImageField(upload_to='contestsRankingPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='contestsYearSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearSemester', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='introductionOfMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('context', models.TextField()),
                ('image', models.ImageField(upload_to='introductionOfMembersImages')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='introductionOfMembersImagesThumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='NewsImages')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='NewsThumbnail')),
                ('author', models.CharField(max_length=50)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updatedDate', models.DateField(auto_now=True)),
                ('context', models.TextField()),
                ('newsOrBlog', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentContests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearSemester', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='studentContestsContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('yearSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.studentContests')),
            ],
        ),
        migrations.CreateModel(
            name='studentContestsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('yearSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.studentContests')),
            ],
        ),
        migrations.CreateModel(
            name='studentContestsimageArchiveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studentContestsimageArchiveList')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='studentContestsimageArchiveListThumbnail')),
                ('yearSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.studentContests')),
            ],
        ),
        migrations.CreateModel(
            name='uiai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearSemester', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UiaiContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('yearSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.uiai')),
            ],
        ),
        migrations.CreateModel(
            name='UiaiFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('yearSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.uiai')),
            ],
        ),
        migrations.CreateModel(
            name='UiaiimageArchiveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='UiaiimageArchiveList')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='UiaiimageArchiveListThumbnail')),
                ('yearSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.uiai')),
            ],
        ),
        migrations.AddField(
            model_name='contests',
            name='yearSemester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.contestsYearSemester'),
        ),
        migrations.AddField(
            model_name='acmconteststeams',
            name='yearSemester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.contestsYearSemester'),
        ),
    ]
