# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acmconteststeams',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='contests',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='introductionofmembers',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-createdDate']},
        ),
        migrations.AlterModelOptions(
            name='studentcontestsfiles',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='studentcontestsimagearchivelist',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='uiai',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='uiaifiles',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='uiaiimagearchivelist',
            options={'ordering': ['-pk']},
        ),
    ]
