# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_auto_20171115_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['createdDate']},
        ),
    ]
