# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20171109_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductionofmembers',
            name='image',
            field=models.ImageField(default=1, upload_to='introductionOfMembersImg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagearchive',
            name='image',
            field=models.ImageField(upload_to='imageArchive'),
        ),
    ]
