# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20171121_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pk']},
        ),
    ]
