# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_auto_20171122_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contests',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentcontestsfiles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uiaifiles',
            options={},
        ),
    ]
