# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_auto_20171122_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uiai',
            options={},
        ),
    ]
